var classes = [
    {
        "name": "Ottonova\\VacationCalculator\\Contract\\Contract",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getStartDate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isSpecial",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSpecialContractVacationDays",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isValidForYear",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Ottonova\\VacationCalculator\\Contract\\ContractInterface",
            "DateTimeImmutable",
            "DateTimeImmutable",
            "DateTimeImmutable"
        ],
        "parents": [],
        "lcom": 1,
        "length": 27,
        "vocabulary": 10,
        "volume": 89.69,
        "difficulty": 7.5,
        "effort": 672.69,
        "level": 0.13,
        "bugs": 0.03,
        "time": 37,
        "intelligentContent": 11.96,
        "number_operators": 12,
        "number_operands": 15,
        "number_operators_unique": 5,
        "number_operands_unique": 5,
        "cloc": 32,
        "loc": 66,
        "lloc": 34,
        "mi": 96.58,
        "mIwoC": 52.52,
        "commentWeight": 44.07,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2.8,
        "relativeSystemComplexity": 3.8,
        "totalStructuralComplexity": 5,
        "totalDataComplexity": 14,
        "totalSystemComplexity": 19,
        "package": "Ottonova\\VacationCalculator\\Contract\\",
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Ottonova\\VacationCalculator\\Calculator\\Rule\\ContractVacationDays",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "apply",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Ottonova\\VacationCalculator\\Calculator\\Rule\\RuleInterface",
            "Ottonova\\VacationCalculator\\Employee\\EmployeeInterface",
            "DateTimeImmutable"
        ],
        "parents": [],
        "lcom": 1,
        "length": 33,
        "vocabulary": 16,
        "volume": 132,
        "difficulty": 6.3,
        "effort": 831.6,
        "level": 0.16,
        "bugs": 0.04,
        "time": 46,
        "intelligentContent": 20.95,
        "number_operators": 12,
        "number_operands": 21,
        "number_operators_unique": 6,
        "number_operands_unique": 10,
        "cloc": 9,
        "loc": 26,
        "lloc": 17,
        "mi": 97.56,
        "mIwoC": 58.04,
        "commentWeight": 39.52,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 25.5,
        "totalStructuralComplexity": 25,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 25.5,
        "package": "Ottonova\\VacationCalculator\\Calculator\\Rule\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Ottonova\\VacationCalculator\\Calculator\\Rule\\AgeBonus",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "apply",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Ottonova\\VacationCalculator\\Calculator\\Rule\\RuleInterface",
            "Ottonova\\VacationCalculator\\Employee\\EmployeeInterface",
            "DateTimeImmutable"
        ],
        "parents": [],
        "lcom": 1,
        "length": 34,
        "vocabulary": 17,
        "volume": 138.97,
        "difficulty": 6,
        "effort": 833.84,
        "level": 0.17,
        "bugs": 0.05,
        "time": 46,
        "intelligentContent": 23.16,
        "number_operators": 12,
        "number_operands": 22,
        "number_operators_unique": 6,
        "number_operands_unique": 11,
        "cloc": 18,
        "loc": 38,
        "lloc": 20,
        "mi": 100.11,
        "mIwoC": 56.35,
        "commentWeight": 43.77,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.8,
        "relativeSystemComplexity": 16.8,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0.8,
        "totalSystemComplexity": 16.8,
        "package": "Ottonova\\VacationCalculator\\Calculator\\Rule\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Ottonova\\VacationCalculator\\Calculator\\Calculator",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "calculate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addRule",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "applyRules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 6,
        "ccnMethodMax": 4,
        "externals": [
            "Ottonova\\VacationCalculator\\Employee\\Collection",
            "DateTimeImmutable",
            "Ottonova\\VacationCalculator\\Calculator\\Rule\\RuleInterface",
            "Ottonova\\VacationCalculator\\Employee\\EmployeeInterface"
        ],
        "parents": [],
        "lcom": 1,
        "length": 42,
        "vocabulary": 13,
        "volume": 155.42,
        "difficulty": 9.69,
        "effort": 1505.62,
        "level": 0.1,
        "bugs": 0.05,
        "time": 84,
        "intelligentContent": 16.04,
        "number_operators": 11,
        "number_operands": 31,
        "number_operators_unique": 5,
        "number_operands_unique": 8,
        "cloc": 29,
        "loc": 65,
        "lloc": 36,
        "mi": 92.89,
        "mIwoC": 49.9,
        "commentWeight": 42.99,
        "kanDefect": 0.75,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 25.5,
        "totalStructuralComplexity": 100,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 102,
        "package": "Ottonova\\VacationCalculator\\Calculator\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Ottonova\\VacationCalculator\\Printer\\CliPrinter",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "print",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Ottonova\\VacationCalculator\\Printer\\PrinterInterface",
            "DateTimeImmutable",
            "Ottonova\\VacationCalculator\\Employee\\Collection"
        ],
        "parents": [],
        "lcom": 1,
        "length": 29,
        "vocabulary": 14,
        "volume": 110.41,
        "difficulty": 3.8,
        "effort": 419.57,
        "level": 0.26,
        "bugs": 0.04,
        "time": 23,
        "intelligentContent": 29.06,
        "number_operators": 10,
        "number_operands": 19,
        "number_operators_unique": 4,
        "number_operands_unique": 10,
        "cloc": 19,
        "loc": 38,
        "lloc": 19,
        "mi": 101.99,
        "mIwoC": 57.53,
        "commentWeight": 44.46,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 9.5,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 19,
        "package": "Ottonova\\VacationCalculator\\Printer\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Ottonova\\VacationCalculator\\Employee\\Factory",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "makeEmployee",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Ottonova\\VacationCalculator\\Employee\\EmployeeInterface",
            "DateTimeImmutable",
            "DateTimeImmutable",
            "Ottonova\\VacationCalculator\\Contract\\Contract",
            "Ottonova\\VacationCalculator\\Employee\\Employee"
        ],
        "parents": [],
        "lcom": 1,
        "length": 16,
        "vocabulary": 8,
        "volume": 48,
        "difficulty": 2.17,
        "effort": 104,
        "level": 0.46,
        "bugs": 0.02,
        "time": 6,
        "intelligentContent": 22.15,
        "number_operators": 3,
        "number_operands": 13,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 11,
        "loc": 22,
        "lloc": 11,
        "mi": 109.83,
        "mIwoC": 65.38,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2.5,
        "relativeSystemComplexity": 3.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 2.5,
        "totalSystemComplexity": 3.5,
        "package": "Ottonova\\VacationCalculator\\Employee\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Ottonova\\VacationCalculator\\Employee\\Employee",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getName",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDateOfBirth",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getContract",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setContract",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setVacationDays",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getVacationDays",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "calculateAge",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 1,
        "wmc": 8,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Ottonova\\VacationCalculator\\Employee\\EmployeeInterface",
            "DateTimeImmutable",
            "DateTimeImmutable",
            "Ottonova\\VacationCalculator\\Contract\\ContractInterface",
            "Ottonova\\VacationCalculator\\Contract\\ContractInterface",
            "DateTimeImmutable"
        ],
        "parents": [],
        "lcom": 1,
        "length": 29,
        "vocabulary": 9,
        "volume": 91.93,
        "difficulty": 2.86,
        "effort": 262.65,
        "level": 0.35,
        "bugs": 0.03,
        "time": 15,
        "intelligentContent": 32.17,
        "number_operators": 9,
        "number_operands": 20,
        "number_operators_unique": 2,
        "number_operands_unique": 7,
        "cloc": 46,
        "loc": 88,
        "lloc": 42,
        "mi": 95.71,
        "mIwoC": 50.71,
        "commentWeight": 45.01,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2.81,
        "relativeSystemComplexity": 3.81,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 22.5,
        "totalSystemComplexity": 30.5,
        "package": "Ottonova\\VacationCalculator\\Employee\\",
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "Ottonova\\VacationCalculator\\Employee\\Collection",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Ottonova\\VacationCalculator\\Employee\\EmployeeInterface"
        ],
        "parents": [],
        "lcom": 1,
        "length": 4,
        "vocabulary": 3,
        "volume": 6.34,
        "difficulty": 0.75,
        "effort": 4.75,
        "level": 1.33,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 8.45,
        "number_operators": 1,
        "number_operands": 3,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 10,
        "loc": 19,
        "lloc": 9,
        "mi": 118.52,
        "mIwoC": 73.43,
        "commentWeight": 45.09,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "Ottonova\\VacationCalculator\\Employee\\",
        "pageRank": 0.06,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "Ottonova\\VacationCalculator\\Data\\DataAttributeEnum",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "lcom": 0,
        "length": 6,
        "vocabulary": 5,
        "volume": 13.93,
        "difficulty": 0,
        "effort": 0,
        "level": 1.67,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 6,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 4,
        "loc": 14,
        "lloc": 10,
        "mi": 106.87,
        "mIwoC": 70.04,
        "commentWeight": 36.83,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Ottonova\\VacationCalculator\\Data\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    }
]